In [1]:
import pandas as pd

In [53]:
df = pd.read_excel('NS_Peak_1.xlsx', sheet_name='商品明細報表', skiprows=1)

In [54]:
df

,STORE,INVOICE,DEPARTMENT,SECTION,SECTION NAME,PRODUCT,PRODUCT_ID,PRICE,QUANTITY,MEMBER
0,1,****5487981015,LIVING PLAZA,709,LIVING PLAZA,TRANSPARENT CUP (SWEET TIME 300ML),***05740873,12.0,1,NaN
1,1,****5487981015,LIVING PLAZA,709,LIVING PLAZA,GENTLE-WASH BODY SPONGE,***05530811,12.0,1,NaN
2,1,****5487989030,MISC-OTHER SALES,864,OTHER,HSBC COUPON $50,***06003735,50.0,15,NaN
3,1,****5488003511,HOUSEHOLD & EA,164,HOUSEKEEPING,TVHC 速乾面巾 黃 (4/96),***30469324,59.9,1,NaN
4,1,****5488011125,FASHION,117,MENS,CONSIG.- S & F INT,***09927005,238.0,1,NaN
...,...,...,...,...,...,...,...,...,...,...
19637,12,****5530161026,FOOD & DELICA,134,DAILY,日本之惠 白蛋 10隻裝,***20284626,28.9,2,*******2022864
19638,12,****5530207506,LIVING PLAZA,709,LIVING PLAZA,PLASTIC HANGING POT MINI WHITE,***50292051,12.0,1,NaN
19639,12,****5530207506,LIVING PLAZA,709,LIVING PLAZA,GLASS VASE(PEAR-SHAPED),***50601376,12.0,2,NaN
19640,12,****5530207506,LIVING PLAZA,709,LIVING PLAZA,BOWL -HEXAGON-4.52IN-BROWN,***50597970,12.0,1,NaN
19641,12,****5530207506,LIVING PLAZA,709,LIVING PLAZA,GLASS VASE(CLEAR LABEL),***50600246,12.0,2,NaN

In [119]:
sales = []
for i in range(len(df)):
    product_sales = df['PRICE'][i]*df['QUANTITY'][i]
    sales.append(product_sales)

In [122]:
df["SALES"] = sales

In [123]:
PB_data = df[df['PRODUCT'].str.startswith('TV')]

In [124]:
PB_data

,STORE,INVOICE,DEPARTMENT,SECTION,SECTION NAME,PRODUCT,PRODUCT_ID,PRICE,QUANTITY,MEMBER,SALES
3,1,****5488003511,HOUSEHOLD & EA,164,HOUSEKEEPING,TVHC 速乾面巾 黃 (4/96),***30469324,59.9,1,NaN,59.9
23,1,****5488109210,HOUSEHOLD & EA,164,HOUSEKEEPING,TVHC 塑膠拖鞋 黑 中 (4/32),***30137400,39.9,2,*******1737810,79.8
117,1,****5488370113,FASHION,113,BABIES,TV123BSI5417 嬰兒即棄紙圍兜-動物,***01271279,19.9,1,*******2121577,19.9
173,1,****5488490020,FOOD & DELICA,131,GROCERY,TV BP 冷麥麵,***20249934,16.9,2,NaN,33.8
222,1,****5488628713,FOOD & DELICA,131,GROCERY,TV 茉莉花茶,***20365409,8.9,1,NaN,8.9
...,...,...,...,...,...,...,...,...,...,...,...
19567,12,****5519755627,HOUSEHOLD & EA,163,KITCHEN & DINING,TVHC 廚房收納盒 (4),***30474100,79.9,1,NaN,79.9
19571,12,****5519755627,HOUSEHOLD & EA,164,HOUSEKEEPING,TVHC 吊掛式伸縮寬肩衣架 (12/96),***30483101,24.9,1,NaN,24.9
19572,12,****5519755627,HOUSEHOLD & EA,163,KITCHEN & DINING,TVHC 輕量陶瓷有耳杯 藍 300毫升(60),***30546022,59.9,1,NaN,59.9
19589,12,****5520080414,FOOD & DELICA,132,LIQUOR,TV BP 芳醇辛口 清酒 900ML,***20242152,37.9,1,NaN,37.9
19593,12,****5520083616,FASHION,112,CHILDREN,TV161AA9002 男童背心(2件裝) WH 130,***11914843,59.0,2,*******2120582,118.0

In [125]:
# No. of PB sales in different stores
PB_data["STORE"].value_counts().sort_index()

1     128
2      70
3      61
4      44
5      41
6      69
7     112
8      73
9      61
10     35
11     65
12     60
Name: STORE, dtype: int64

In [126]:
# No. of PB sales in different categories
PB_data["DEPARTMENT"].value_counts()

FOOD & DELICA     449
HOUSEHOLD & EA    279
FASHION            91
Name: DEPARTMENT, dtype: int64

In [137]:
# PB sales in different categories
PB_data.groupby("DEPARTMENT")["SALES"].sum().sort_values(ascending=False)

DEPARTMENT
HOUSEHOLD & EA    18179.3
FOOD & DELICA      9807.9
FASHION            8443.4
Name: SALES, dtype: float64

In [141]:
PB_data.loc[PB_data["DEPARTMENT"] == "HOUSEHOLD & EA"]["SECTION NAME"].value_counts()

KITCHEN & DINING        105
HOUSEKEEPING             70
NON FOOD                 59
FURNITURE & INTERIOR     18
BEDDING                  15
COSMETIC                 11
HEALTH                    1
Name: SECTION NAME, dtype: int64

### Memebership

In [100]:
PB_member = PB_data[PB_data["MEMBER"].notna()]

In [108]:
PB_member

,STORE,INVOICE,DEPARTMENT,SECTION,SECTION NAME,PRODUCT,PRODUCT_ID,PRICE,QUANTITY,MEMBER
23,1,****5488109210,HOUSEHOLD & EA,164,HOUSEKEEPING,TVHC 塑膠拖鞋 黑 中 (4/32),***30137400,39.9,2,*******1737810
117,1,****5488370113,FASHION,113,BABIES,TV123BSI5417 嬰兒即棄紙圍兜-動物,***01271279,19.9,1,*******2121577
257,1,****5488693511,FOOD & DELICA,131,GROCERY,TV GE 有機麥茶茶包,***20243473,22.9,2,*******2073181
452,1,****5489102028,HOUSEHOLD & EA,162,FURNITURE & INTERIOR,TVHC 記憶棉圓形座墊 灰藍(6),***30452445,129.0,1,*******1746400
465,1,****5489119021,FOOD & DELICA,131,GROCERY,TV BP 烏龍茶 2000ML,***20365441,14.9,2,*******2091688
...,...,...,...,...,...,...,...,...,...,...
19056,12,****5507649512,FOOD & DELICA,131,GROCERY,TV BP 即沖味噌湯 海帶口味,***20279683,8.9,2,*******2030949
19319,12,****5517366322,FASHION,118,UNDERWEAR,TV158BA1622G 男裝有機綿短袖V領內衣2P(淨) WH M,***11888898,99.0,1,*******2123955
19379,12,****5518006608,FOOD & DELICA,131,GROCERY,TV BP 卡邦尼白汁煙肉芝士意粉醬,***20223178,9.9,1,*******2013510
19543,12,****5519631318,FOOD & DELICA,133,DELICA,TV 肉薯餅(2件),***00205286,12.9,1,*******2006419
19593,12,****5520083616,FASHION,112,CHILDREN,TV161AA9002 男童背心(2件裝) WH 130,***11914843,59.0,2,*******2120582

In [109]:
# No. of PB sales in different stores (member)
PB_member["STORE"].value_counts().sort_index()

1     39
2     17
3     15
4     12
5      8
6      9
7     38
8     22
9     14
10     7
11     5
12    18
Name: STORE, dtype: int64

In [110]:
# No. of PB sales in different categories
PB_member["DEPARTMENT"].value_counts()

FOOD & DELICA     113
HOUSEHOLD & EA     57
FASHION            34
Name: DEPARTMENT, dtype: int64